version: '3.8'
services:
  web:
    build: ./plant_tracker_back
    command: bash -c "python -u manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./plant_tracker_back/:/project/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - plant_tracker_back/.env
    environment:
      PYTHONUNBUFFERED: 1
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: ./plant_tracker_front
    command: bash -c "npm run dev"
    volumes:
      - ./plant_tracker_front/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    depends_on:
     - web
    env_file:
    - plant_tracker_front/.env.local
volumes:
  postgres_data:
